import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: uuid(),
    firstName: "Prince",
    lastName: "Raj",
    username: "princeraj",
    // email: "princeraj@gmail.com",
    password: "12345",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },

  {
    _id: uuid(),
    firstName: "John",
    lastName: "Doe",
    username: "johnd",
    password: "password123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/johnd.jpg",
    bio: "I'm just a regular person.",
    website: "https://example.com/johnd",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jane",
    lastName: "Smith",
    username: "janes",
    password: "test456",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/janes.jpg",
    bio: "Lover of books and coffee.",
    website: "https://example.com/janes",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "David",
    lastName: "Johnson",
    username: "davidj",
    password: "pass123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/davidj.jpg",
    bio: "Adventure seeker and nature lover.",
    website: "https://example.com/davidj",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Emily",
    lastName: "Brown",
    username: "emilyb",
    password: "letmein",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/emilyb.jpg",
    bio: "Photography enthusiast and traveler.",
    website: "https://example.com/emilyb",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Michael",
    lastName: "Wilson",
    username: "michaelw",
    password: "qwerty123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/michaelw.jpg",
    bio: "Music lover and guitar player.",
    website: "https://example.com/michaelw",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Sophia",
    lastName: "Jones",
    username: "sophiaj",
    password: "mypassword",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/sophiaj.jpg",
    bio: "Foodie and aspiring chef.",
    website: "https://example.com/sophiaj",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "William",
    lastName: "Davis",
    username: "williamd",
    password: "welcome1",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/williamd.jpg",
    bio: "Sports enthusiast and fitness freak.",
    website: "https://example.com/williamd",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mia",
    lastName: "Clark",
    username: "miacl",
    password: "mia123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/miacl.jpg",
    bio: "Fashion enthusiast and trendsetter.",
    website: "https://example.com/miacl",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Daniel",
    lastName: "Miller",
    username: "danielm",
    password: "daniel123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/danielm.jpg",
    bio: "Tech geek and software developer.",
    website: "https://example.com/danielm",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ava",
    lastName: "Taylor",
    username: "avat",
    password: "password123",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/avat.jpg",
    bio: "Art lover and aspiring painter.",
    website: "https://example.com/avat",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Liam",
    lastName: "Anderson",
    username: "liama",
    password: "password456",
    following: [],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/liama.jpg",
    bio: "Nature lover and hiking enthusiast.",
    website: "https://example.com/liama",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
