import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
  {
    _id: 1,
    firstName: "Adarsh",
    lastName: "User",
    username: "adarshuserhu",
    password: "adarshUser123",
    userHandler: "adarshuser24",
    bio: "let Go",
    following: [],
    followers: [],
    bookmarks: [],
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },

  {
    _id: uuid(),
    firstName: "Prince",
    lastName: "Raj",
    username: "princeraj",
    // email: "princeraj@gmail.com",
    following: [
      {
        _id: uuid(),
        fullName: "Sarahana Singh",
        username: "kittuaa",
        profilePicture: "",
      },
    ],
    followers: [
      {
        _id: uuid(),
        fullName: "Sarahana Singh",
        username: "kittuaa",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Jane Smith",
        username: "janes",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "David Johnson",
        username: "dadidj",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Emily Brown",
        username: "emilyb",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Michael Wilson",
        username: "michaelw",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Sophia Jones",
        username: "sophiaj",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "William Davis",
        username: "williamd",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Mia Clark",
        username: "miacl",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Daniel Miller",
        username: "danielm",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Ava Taylor",
        username: "avat",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Liam Anderson",
        username: "liama",
        profilePicture: "",
      },
    ],
    bookmarks: [],
    profilePicture: "",
    bio: "Astrologer 🔯 Developer 👨‍💻 Fitness Freak",
    password: "12345",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },

  {
    _id: uuid(),
    firstName: "Sarahana",
    lastName: "Singh",
    username: "kittuaa",
    password: "password123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Jane Smith",
        username: "janes",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "David Johnson",
        username: "dadidj",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Emily Brown",
        username: "emilyb",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Michael Wilson",
        username: "michaelw",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Sophia Jones",
        username: "sophiaj",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "William Davis",
        username: "williamd",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Mia Clark",
        username: "miacl",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Daniel Miller",
        username: "danielm",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Ava Taylor",
        username: "avat",
        profilePicture: "",
      },
      {
        _id: uuid(),
        fullName: "Liam Anderson",
        username: "liama",
        profilePicture: "",
      },
    ],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/johnd.jpg",
    bio: "In oneword Celebrity",
    website: "https://example.com/johnd",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Jane",
    lastName: "Smith",
    username: "janes",
    password: "test456",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/janes.jpg",
    bio: "Lover of books and coffee.",
    website: "https://example.com/janes",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "David",
    lastName: "Johnson",
    username: "davidj",
    password: "pass123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/davidj.jpg",
    bio: "Adventure seeker and nature lover.",
    website: "https://example.com/davidj",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Emily",
    lastName: "Brown",
    username: "emilyb",
    password: "letmein",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/emilyb.jpg",
    bio: "Photography enthusiast and traveler.",
    website: "https://example.com/emilyb",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Michael",
    lastName: "Wilson",
    username: "michaelw",
    password: "qwerty123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/michaelw.jpg",
    bio: "Music lover and guitar player.",
    website: "https://example.com/michaelw",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Sophia",
    lastName: "Jones",
    username: "sophiaj",
    password: "mypassword",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/sophiaj.jpg",
    bio: "Foodie and aspiring chef.",
    website: "https://example.com/sophiaj",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "William",
    lastName: "Davis",
    username: "williamd",
    password: "welcome1",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/williamd.jpg",
    bio: "Sports enthusiast and fitness freak.",
    website: "https://example.com/williamd",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Mia",
    lastName: "Clark",
    username: "miacl",
    password: "mia123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/miacl.jpg",
    bio: "Fashion enthusiast and trendsetter.",
    website: "https://example.com/miacl",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Daniel",
    lastName: "Miller",
    username: "danielm",
    password: "daniel123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/danielm.jpg",
    bio: "Tech geek and software developer.",
    website: "https://example.com/danielm",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Ava",
    lastName: "Taylor",
    username: "avat",
    password: "password123",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/avat.jpg",
    bio: "Art lover and aspiring painter.",
    website: "https://example.com/avat",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName: "Liam",
    lastName: "Anderson",
    username: "liama",
    password: "password456",
    following: [
      {
        _id: uuid(),
        fullName: "Prince Raj",
        username: "princeraj",
        profilePicture: "",
      },
    ],
    followers: [],
    bookmarks: [],
    profilePicture: "https://example.com/profile-picture/liama.jpg",
    bio: "Nature lover and hiking enthusiast.",
    website: "https://example.com/liama",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
